<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Admin Profile</title>
<link rel="stylesheet" type="text/css" href="Style/viewtablesearch.css" />

</head>
<body>	
	<center><div class="img"><img src="Images/logo.jpg" /></div></center>
	<br><center><font size="40" color="white">Bangladesh University of Business and Technology</font></center>
	<center><h1><font color="white">Student Information System</font></h1></center>
<br><br><br>	
<center>

<a href="routine_admin.php">
<img src="Images/routine.png"  width="130" height="120" border="0"/>
</a>


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

<a href="view_library_admin.php">
<img src="Images/library.png"  width="130" height="120" border="0"/>
</a>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

<a href="result_admin.php" target="_blank">
<img src="Images/result.jpg"  width="130" height="120" border="0"/>
</a>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

<a href="registration_admin.php" target="_blank">
<img src="Images/reg.png"  width="130" height="120" border="0"/>
</a>

</center>
<br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&emsp;&emsp;&emsp;&emsp;
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
<font color="white " size="4"><b>Routine</b></font>

&nbsp;&nbsp;&nbsp;&nbsp;
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
<font color="white " size="4"><b>Library</b></font>
&nbsp;&nbsp;&nbsp;&nbsp;&emsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&emsp;&emsp;&emsp;&nbsp;&emsp;
<font color="white " size="4"><b>Result</b></font>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&emsp;&emsp;&emsp;&nbsp;&emsp;&nbsp;&nbsp;
<font color="white " size="4"><b>Course</b></font>

</body>
</html>